In [12]:
import numpy as np
import pandas as pd

In [7]:
a = np.array(['cat','dog','fish'])
b = np.array(['bird','ant','fish'])
print(np.setdiff1d(a,b))

['cat' 'dog']


In [4]:
print(np.setdiff1d(b,a))

['ant' 'bird']


In [48]:
c = np.array([1,2,3,4])
d = np.array([[1,1],[1,1]])

In [49]:
c + d

ValueError: operands could not be broadcast together with shapes (4,) (2,2) 

In [51]:
p= np.array([[1],[1]])
q= np.array([[1,2],[3,4]])
r = p+q
r

array([[2, 3],
       [4, 5]])

In [52]:
t= np.array([[1,1]])
u= np.array([[1,2],[3,4]])
v = t+u
v

array([[2, 3],
       [4, 5]])

In [53]:
w= np.array([[1,1,1]])
x= np.array([[1,2],[3,4]])
y = w+x


ValueError: operands could not be broadcast together with shapes (1,3) (2,2) 

In [14]:
x = np.array(['apple','orange'])

In [17]:
y = pd.Series(x)

In [24]:
y.loc[[0,1]]

0     apple
1    orange
dtype: object

In [54]:
import pandas as pd
ser = pd.Series([100, 200, 300, 400, 500], index = ['tom', 'bob', 'nancy', 'dan', 'eric'])

In [56]:
ser[['tom','bob']]

tom    100
bob    200
dtype: int64

In [57]:
ser[[0,1]]

tom    100
bob    200
dtype: int64

In [59]:
ser.loc[['tom','bob']]

tom    100
bob    200
dtype: int64

In [60]:
ser.iloc[[0,1]]

tom    100
bob    200
dtype: int64

In [25]:
import json

In [26]:
status = ['like','excited','wow','dislike'] 

In [34]:
print(json.dumps(status[0:3],indent=1))

[
 "like",
 "excited",
 "wow"
]


In [35]:
m = np.array([[1,2,3],[4,5,6]])
n = m[:2,1:3]

In [36]:
n

array([[2, 3],
       [5, 6]])

In [37]:
n[0,0] = 9

In [38]:
m

array([[1, 9, 3],
       [4, 5, 6]])

In [44]:
np.ndim(m)

2

In [45]:
m.sum()

28

In [47]:
pass

In [61]:
m.describe()

AttributeError: 'numpy.ndarray' object has no attribute 'describe'

In [80]:
d = {'one' : pd.Series([100.,200.,23.,34.,555.], index=['apple','orange','tomato','berries','pear']), 
     'two' : pd.Series([111.,211,1.,1.,1.], index=['apple','orange','tomato','berries','pear']),
     'three' : pd.Series([111.,211,1.,1.,1.], index=['apple','orange','tomato','berries','pear'])
    }
df = pd.DataFrame(d)
filter = df['one']>100
filter.any()

True

In [70]:
filter = df['one']>111

In [71]:
xx

apple     False
orange     True
Name: one, dtype: bool

In [72]:
xx.any()

True

In [109]:
df['Y']=1
df

one    two  three  Y
apple    100.0  111.0  111.0  1
orange   200.0  211.0  211.0  1
tomato    23.0    1.0    1.0  1
berries   34.0    1.0    1.0  1
pear     555.0    1.0    1.0  1

In [110]:
df.at['apple','Y']=0
df.at['pear','Y']=0
df.at['orange','Y']=0
df

one    two  three  Y
apple    100.0  111.0  111.0  0
orange   200.0  211.0  211.0  0
tomato    23.0    1.0    1.0  1
berries   34.0    1.0    1.0  1
pear     555.0    1.0    1.0  0

In [82]:
df.isnull().any()

one      False
two      False
three    False
dtype: bool

In [85]:
31 % 3

1

In [86]:
str = 'my name is raheel'
strdf = str.split(expand=True)

TypeError: 'expand' is an invalid keyword argument for split()

In [87]:
d

{'one': apple      100.0
 orange     200.0
 tomato      23.0
 berries     34.0
 pear       555.0
 dtype: float64,
 'two': apple      111.0
 orange     211.0
 tomato       1.0
 berries      1.0
 pear         1.0
 dtype: float64,
 'three': apple      111.0
 orange     211.0
 tomato       1.0
 berries      1.0
 pear         1.0
 dtype: float64}

In [88]:
strdf = d.split(expand=True)

AttributeError: 'dict' object has no attribute 'split'

In [93]:
pp = pd.Series(['one','two','three','four','five'], index=['apple','orange','tomato','berries','pear'])

In [94]:
pp

apple        one
orange       two
tomato     three
berries     four
pear        five
dtype: object

In [98]:
dfx = pp.str.split(expand=False)

In [99]:
type(dfx)

pandas.core.series.Series

In [100]:
dfx

apple        [one]
orange       [two]
tomato     [three]
berries     [four]
pear        [five]
dtype: object

In [103]:
b = [10,3,4,5,7]

for x in b:
    print('{:^10}'.format(x))

    10    
    3     
    4     
    5     
    7     


In [105]:
for x in b:
    print('{:<10} 2'.format(x))

10         2
3          2
4          2
5          2
7          2


In [106]:
for x in b:
    print('{:>10} 2'.format(x))

        10 2
         3 2
         4 2
         5 2
         7 2


In [107]:
df

one    two  three
apple    100.0  111.0  111.0
orange   200.0  211.0  211.0
tomato    23.0    1.0    1.0
berries   34.0    1.0    1.0
pear     555.0    1.0    1.0

In [108]:
from sklearn.model_selection import train_test_split

In [111]:
y = df['Y']
X = df.drop(['Y'], axis=1)

In [156]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

In [157]:
X_train

one    two  three
tomato    23.0    1.0    1.0
berries   34.0    1.0    1.0
apple    100.0  111.0  111.0

In [158]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

In [159]:
X_train

one    two  three
orange   200.0  211.0  211.0
berries   34.0    1.0    1.0
apple    100.0  111.0  111.0

In [126]:
df.nunique()>2

one       True
two       True
three     True
Y        False
dtype: bool

In [161]:
df.describe()

one         two       three         Y
count    5.000000    5.000000    5.000000  5.000000
mean   182.400000   65.000000   65.000000  0.400000
std    219.864276   94.498677   94.498677  0.547723
min     23.000000    1.000000    1.000000  0.000000
25%     34.000000    1.000000    1.000000  0.000000
50%    100.000000    1.000000    1.000000  0.000000
75%    200.000000  111.000000  111.000000  1.000000
max    555.000000  211.000000  211.000000  1.000000